theme:      "night"
transition: "page"
author:     "Shunsuke Kirino"
title:      "Advice for New Graduates"
revealjs_config:
  dependencies:
    - src:   "plugin/math/math.js"
      async: true
  math:
    mathjax: "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js"
