theme:      "simple"
transition: "page"
author:     "Shunsuke Kirino"
title:      "Antikythera Framework"
revealjs_config:
  controls: true
  slideNumber: true
  history: true
  dependencies:
    - src:   "plugin/math/math.js"
      async: true
  math:
    mathjax: "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js"
